language: node_js
node_js:
- '4'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
before_install:
- export CC="gcc-4.9 -std=c99" CXX="g++-4.9"
deploy:
  provider: npm
  email: seb.cottinet@gmail.com
  api_key:
    secure: DQAx5lLwuFnI+2PXteV1/FHkX15+nLMmdXYvwvSOLUtJy0q1Qv0JOkugw4z29ZW5ewvWRfABRt6BH/XQsmT/q9zStFQAWLlPmFM8fX4H1r37C6SaAN7lOkQAN4vtI74TKH9DrbTppTq4j7TeBwu94ELc+lNHxCT/XkjhR9lRO4mLzLYhgd/ORNphDntjJ4gSlJMNyvEPHutx2le1MCilJQy0YSGRNPRuH4w+tK8xvNDn64A/czD2aXsS7DxH66vQrB2qDV7ZBlAfZ+E2h3Bux8C/p+uc3mCwSIG0rFxI7/vhwAcGFvVjbJj24f0B+lwZ2ikYfeUr/LI35WMt2XS0k2Mj9VUTZQslrXr8TMjNYkO2ip6coDSxYltEfgFUiGkQy/sD6CTOmgXJ3tP9KirP8skuTiwvHMUT6BwhQCneEuIa8razS/yJ8mcz45buh3OFZBgcDuV1cWyN6lw4YJIs250S5t+6t1bVYYxkCuDMDeA5or3g41YD4yftaOUMf7CcrgcfmMycwrwkljvIvdPlkdabm5Jzs6N7PFhJm0yEgwA1FNncIwPQAU0OEPWJVE4lCuthkjz/v0+1rA6etckHzKBd0D58he7mengYvqTqbQ07731OMNSqG32lLCNYVOXQETPWr1l2pO+MykRcOJDuFYffAJGg9JO329xldvlk+cY=
  on:
    repo: scottinet/espresso-logic-minimizer
    branch: master
